### PR TITLE
Removed X

### PR DESCRIPTION
**Pull request by Akatroj**

### CODE REVIEW

**Review by delekta — APPROVED** [review]
LGTM

**Comment by DawidGrapa** [comment]
u sure it wont affect the code?

**Comment by mario11-wiet** [comment]
Good job !!!!!!!!!!!!!

**Review by mario11-wiet — APPROVED** [review]

**Review by DawidGrapa — APPROVED** [review]

**Review by dimamik — COMMENTED** [review]
Great job, nice catch!

**Pull request merged**
